"""empty message

Revision ID: 5c3c62c3af99
Revises: 68edb88591e7
Create Date: 2022-08-02 13:06:10.545773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c3c62c3af99'
down_revision = '68edb88591e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('header_img', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'header_img')
    # ### end Alembic commands ###
