export const Facts = [
    "Fleas can jump 350 times its body length.",
    "Hummingbirds are the only birds that can fly backwards.",
    "Crocodiles cannot stick their tongue out.",
    "Starfish do not have a brain.",
    "Slugs have 4 noses.",
    "Only female mosquitoes bite.",
    "Polar bear skin is black!",
    "The only mammal capable of flight is the bat.",
    "A newborn kangaroo is the size of a lima bean.",
    "Cats have 32 muscles in each ear.",
    "Cats have 4 rows of whiskers.",
    "Cats have no collarbone, which is one reason they are so flexible.",
    "Cats spend approximately 30% of their waking hours grooming themselves.",
    "American Shorthair is the designation reserved for pedigreed cats, while similar-looking cats of mixed or unknown origin are called domestic shorthairs.",
    "The jaw of a feline cannot move sideways.",
    "Cats have over one hundred vocal sounds, while dogs have about ten!",
    "Cat whiskers are so sensitive they can detect the slightest change in air current.",
    "Cats have 26 baby teeth and 30 permanent teeth.",
    "Dalmatians are born without spots!  They are born with plain white coats with their first spots appearing after they are 1week old.",
    "Dogs sweat through their foot pads to help keep them cool.  They also keep cool by panting.",
    "Greyhounds are the world’s fastest dogs with the ability to reach up to 45 mph.",
    "Every dog has a unique nose print with no two alike.",
    "The Basenji, an African wolf dog, does not bark in a normal way but may yodel or scream when excited!",
    "Snoopy, from Charles M. Schultz’s “Peanuts” comic strip, is a beagle.",
    "A dog’s sense of smell is 1000 times greater than a human!",
    "Nine percent of dog owners will have a birthday party for their pet.",
    "Dogs have 28 baby teeth and 42 permanent teeth.",
]